apiVersion: v1
kind: Service
metadata:
  name: ced-webpage-dev
  namespace: ced-devops-cicd-dev
spec:
  selector:
    app: ced-webpage-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31805
  type: NodePort

